export const categoryOptions = [
    { value: "other", label: "Other" },
    { value: "adult", label: "Adult" },
    { value: "arts", label: "Arts" },
    { value: "charity", label: "Charity" },
    { value: "cinema-film", label: "Cinema & Film"},
    { value: "community", label: "Community" },
    { value: "crafts", label: "Crafts" },
    { value: "culture", label: "Culture" },
    { value: "education", label: "Education" },
    { value: "environment", label: "Environment" },
    { value: "family", label: "Family" },
    { value: "fashion", label: "Fashion" },
    { value: "fitness", label: "Fitness" },
    { value: "food-drink", label: "Food & Drink" },
    { value: "gaming", label: "Gaming" },
    { value: "holiday-seasonal", label: "Holiday & Seasonal" },
    { value: "music", label: "Music" },
    { value: "nightlife", label: "Nightlife" },
    { value: "performing-arts", label: "Performing Arts" },
    { value: "politics", label: "Politics" },
    { value: "professional", label: "Professional" },
    { value: "religion", label: "Religion" },
    { value: "sports", label: "Sports" },
    { value: "technology", label: "Technology" },
    { value: "travel", label: "Travel" },
    { value: "wellness", label: "Wellness" },
];

export const formatOptions = [
    { value: "in-person", label: "In-Person" },
    { value: "online", label: "Online" },
    { value: "hybrid", label: "Hybrid" },
];

export const neighborhoodOptions: Record<string, { value: string, label: string }[]> = {
    seattle: [
        { value: "other", label: "Other" },
        { value: "ballard", label: "Ballard" },
        { value: "belltown", label: "Belltown" },
        { value: "bellevue", label: "Bellevue" },
        { value: "beacon-hill", label: "Beacon Hill" },
        { value: "broadway", label: "Broadway" },
        { value: "capitol-hill", label: "Capitol Hill" },
        { value: "central-district", label: "Central District" },
        { value: "columbia-city", label: "Columbia City" },
        { value: "downton", label: "Downtown" },
        { value: "eastlake", label: "Eastlake" },
        { value: "first-hill", label: "First Hill" },
        { value: "fremont", label: "Fremont" },
        { value: "georgetown", label: "Georgetown" },
        { value: "greenlake", label: "Greenlake" },
        { value: "international-district", label: "International District (Chinatown)" },
        { value: "laurelhurst", label: "Laurelhurst" },
        { value: "madison-park", label: "Madison Park" },
        { value: "madrona", label: "Madrona" },
        { value: "magnolia", label: "Magnolia" },
        { value: "mount-baker", label: "Mount Baker" },
        { value: "northgate", label: "Northgate" },
        { value: "pioneer-square", label: "Pioneer Square" },
        { value: "puyallup", label: "Puyallup" },
        { value: "queen-anne", label: "Queen Anne" },
        { value: "rainier-valley", label: "Rainier Valley" },
        { value: "ravenna", label: "Ravenna" },
        { value: "sodo", label: "SODO" },
        { value: "south-lake-union", label: "South Lake Union" },
        { value: "university-district", label: "University District" },
        { value: "wallingford", label: "Wallingford" },
        { value: "westlake", label: "Westlake" },
        { value: "west-seattle", label: "West Seattle" },
    ],
    portland: [
        { value: "other", label: "Other" },
        { value: "downtown", label: "Downtown" },
        { value: "pearl-district", label: "Pearl District" },
        { value: "nob-hill", label: "Nob Hill" },
        { value: "hawthorne", label: "Hawthorne" },
    ],
    'los-angeles': [
        { value: "other", label: "Other" },
        { value: "downtown", label: "Downtown" },
        { value: "venice", label: "Venice" },
        { value: "koreatown", label: "Koreatown" },
        { value: "little-tokyo", label: "Little Tokyo" },
    ],
    'san-francisco': [
        { value: "other", label: "Other" },
        { value: "mission-district", label: "Mission District" },
        { value: "north-beach", label: "North Beach" },
        { value: "soma", label: "SOMA" },
        { value: "nob-hill", label: "Nob Hill" },
    ],
};

export const costOptions = [
    { value: "free", label: "Free" },
    { value: "$0-$25", label: "$0-$25" },
    { value: "$25-$50", label: "$25-$50" },
    { value: "$50-$100", label: "$50-$100" },
    { value: "$100+", label: "$100+" },
];

export const cityOptions = [
    { value: "seattle", label: "Seattle" },
    { value: "portland", label: "Portland" },
    { value: "los-angeles", label: "Los Angeles" },
    { value: "san-francisco", label: "San Francisco" },
];