export const events = [
  {
    id: "e4ff1477-cb82-4139-a952-04f9dedf8e3b",
    name: "Diplo's Run Club",
    date: "September 14, 2024",
    time: "9:00 AM - 12:00 PM",
    location: "Gas Works Park",
    cost: "$100",
    subject: "Join us for a thrilling run along the scenic waterfront followed by a music festival like no other.",
    description: "Diplo's Run Club combines fitness with entertainment, offering participants a unique experience of a morning run at Gas Works Park, followed by a live music festival headlined by Diplo himself. It's a perfect blend of exercise and entertainment for those looking to kick off their weekend on a high note.",
    link: "https://diplosrunclub.com/seattle",
    image: "",
    category: "Fitness",
    tags: ["Run", "music", "diplo"]
  },
  {
    id: "e2ff1567-cb82-4139-bb3c-04f8dedf7b3a",
    name: "Seattle Book Fair",
    date: "October 14-15, 2024",
    time: "10:00 AM - 5:00 PM",
    location: "Seattle Center",
    cost: "$10",
    subject: "Browse thousands of collectible and antique books, maps, and posters.",
    description: "The Seattle Book Fair is a must-attend event for bibliophiles and collectors alike. This annual event brings together sellers and enthusiasts of rare and antique books, offering a wide range of books, maps, posters, and more. It's a fantastic opportunity to find unique literary treasures while supporting the local book community.",
    link: "https://www.seattlebookfair.com",
    image: "",
    category: "Books & Literature",
    tags: ["books", "fair", "collectibles"]
  },
  {
    id: "e3ff1677-cb82-4139-cc3c-04f7dedf8c4c",
    name: "Mead Festival",
    date: "October 15, 2024",
    time: "12:00 PM - 4:00 PM",
    location: "Skål Beer Hall",
    cost: "$30",
    subject: "Sample a wide range of local Washington meads.",
    description: "The Mead Festival at Skål Beer Hall offers a unique tasting experience for fans of this ancient fermented drink. Attendees can sample a variety of meads made from local Washington ingredients, learn about the history and production of mead, and enjoy a day of drinks, food, and community at one of Seattle's favorite beer halls.",
    link: "https://www.eventbrite.com/meadfestival",
    image: "",
    category: "Food & Drink",
    tags: ["mead", "festival", "drinks"]
  },
  {
    id: "e5ff1877-cb82-4139-ee4c-04f5dedf8e6e",
    name: "Carnevolar XI: DéComposition",
    date: "October 20, 2024",
    time: "7:00 PM - 11:00 PM",
    location: "Emerald City Trapeze Arts",
    cost: "$40",
    subject: "Halloween circus show and dance party.",
    description: "Carnevolar XI: DéComposition is an electrifying Halloween event featuring a circus performance that blends aerial arts with a spooky theme. Held at Emerald City Trapeze Arts, this event culminates in a vibrant dance party, offering a thrilling night of entertainment and celebration in the spirit of Halloween.",
    link: "https://www.emeraldcitytrapeze.com/carnevolar",
    image: "",
    category: "Performing Arts",
    tags: ["halloween", "circus", "dance"]
  },
  {
    id: "e6ff1977-cb82-4139-ff5c-04f4dedf9f7f",
    name: "Ballard Wine Walk",
    date: "October 21, 2024",
    time: "5:00 PM - 9:00 PM",
    location: "Ballard Neighborhood",
    cost: "$40",
    subject: "Explore local wines paired with boutique shops.",
    description: "The Ballard Wine Walk is an annual event where participants can enjoy a curated selection of wines from local Washington wineries while strolling through the charming Ballard neighborhood. Each wine stop is paired with a boutique shop, making it a delightful evening of wine tasting and shopping in one of Seattle's trendiest areas.",
    link: "https://www.eventbrite.com/ballardwinewalk",
    image: "",
    category: "Food & Drink",
    tags: ["wine", "walk", "local"]
  },
  {
    id: "e7ff2077-cb82-4139-gg6c-04f3dedf0g8g",
    name: "Survive Seattle: Zombie Run",
    date: "October 21-22, 2024",
    time: "10:00 AM - 2:00 PM",
    location: "Jefferson Park",
    cost: "$35",
    subject: "Run through an obstacle course while avoiding zombies.",
    description: "Survive Seattle: Zombie Run is a unique and adrenaline-pumping event where participants race through an obstacle course while being chased by zombies. The event is designed to be both challenging and fun, with the goal of escaping the undead and making it to the finish line. It's a perfect blend of fitness and Halloween thrills.",
    link: "https://www.winwithwarriors.org/zombierun",
    image: "",
    category: "Fitness",
    tags: ["run", "zombies", "fitness"]
  },
  {
    id: "e8ff2177-cb82-4139-hh7c-04f2dedf1h9h",
    name: "West Seattle Monster Dash",
    date: "October 28, 2024",
    time: "9:00 AM - 12:00 PM",
    location: "Lincoln Park",
    cost: "$25",
    subject: "5k run/walk with a Halloween costume contest.",
    description: "The West Seattle Monster Dash is a family-friendly 5K run/walk held at Lincoln Park. Participants are encouraged to dress in their best Halloween costumes, adding a festive and spooky element to the race. The event includes a costume contest and is a fun way for the community to get active and celebrate Halloween together.",
    link: "https://www.runsignup.com/monsterdamash",
    image: "",
    category: "Fitness",
    tags: ["run", "halloween", "costume"]
  },
  {
    id: "e9ff2277-cb82-4139-ii8c-04f1dedf2i1i",
    name: "Seattle Restaurant Week",
    date: "October 22 - November 4, 2024",
    time: "Varies",
    location: "Various Locations",
    cost: "Varies",
    subject: "Fixed-price menus at participating Seattle restaurants.",
    description: "Seattle Restaurant Week is a biannual event that celebrates the city's culinary scene. During this time, participating restaurants offer special fixed-price menus that allow diners to experience a variety of dishes at an affordable price. It's a great opportunity to explore new eateries or revisit old favorites while supporting local businesses.",
    link: "https://www.srweek.org",
    image: "",
    category: "Food & Drink",
    tags: ["food", "restaurant", "week"]
  },
  {
    id: "eaff2377-cb82-4139-jj9c-04f0dedf3j2j",
    name: "Boo! Halloween Music Festival",
    date: "October 27-28, 2024",
    time: "6:00 PM - 2:00 AM",
    location: "WAMU Theater",
    cost: "$50",
    subject: "Live music festival with Halloween-themed performances.",
    description: "Boo! Halloween Music Festival is a two-day event featuring live performances from top artists, all with a Halloween twist. Held at WAMU Theater, this festival combines the thrill of live music with the excitement of Halloween, offering a unique and immersive experience for attendees. Costumes are highly encouraged!",
    link: "https://www.seattle.boo-halloween.com",
    image: "",
    category: "Music",
    tags: ["music", "halloween", "festival"]
  },
  {
    id: "edff2677-cb82-4139-mm2c-04dedf6m5m",
    name: "Dia de Muertos Festival",
    date: "October 28-29, 2024",
    time: "11:00 AM - 5:00 PM",
    location: "Seattle Center",
    cost: "Free",
    subject: "Celebrate Dia de Muertos with live performances and cultural displays.",
    description: "The Dia de Muertos Festival at Seattle Center is a vibrant celebration of Mexican culture, honoring the Day of the Dead. This free event features traditional music, dance performances, art installations, and altar displays. It's an opportunity for the community to come together and experience the rich cultural traditions associated with this important holiday.",
    link: "https://www.seattlecenter.com/diademuertos",
    image: "",
    category: "Cultural",
    tags: ["festival", "cultural", "muertos"]
  },
  {
    id: "ebff2477-cb82-4139-kk0c-04efdedf4k3k",
    name: "Museum of Fright",
    date: "October 29, 2024",
    time: "10:00 AM - 5:00 PM",
    location: "Museum of Flight",
    cost: "Included with admission",
    subject: "Halloween games and activities for all ages.",
    description: "The Museum of Fright transforms the Museum of Flight into a Halloween wonderland, offering a mix of spooky fun and educational activities for children and adults. Visitors can participate in themed games, enjoy special exhibits, and take part in family-friendly activities that blend the excitement of Halloween with the marvels of aviation.",
    link: "https://www.museumofflight.org/museumoffright",
    image: "",
    category: "Family",
    tags: ["museum", "halloween", "family"]
  }
]

export type Event = (typeof events)[number]